//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2CServer.TMCTransportInfrastructureAsset {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/transport_network/TransportInfras" +
        "tructureAsset_v0p1")]
    public partial class errorReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorReport errorReportMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tmdd.org/3/messages", Order=0)]
        public ErrorReport errorReportMsg {
            get {
                return this.errorReportMsgField;
            }
            set {
                this.errorReportMsgField = value;
                this.RaisePropertyChanged("errorReportMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class ErrorReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Restrictions restrictionsField;
        
        private OrganizationInformation organizationinformationField;
        
        private OrganizationInformation organizationrequestingField;
        
        private string errorcodeField;
        
        private string errortextField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Restrictions restrictions {
            get {
                return this.restrictionsField;
            }
            set {
                this.restrictionsField = value;
                this.RaisePropertyChanged("restrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public OrganizationInformation organizationinformation {
            get {
                return this.organizationinformationField;
            }
            set {
                this.organizationinformationField = value;
                this.RaisePropertyChanged("organizationinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-requesting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public OrganizationInformation organizationrequesting {
            get {
                return this.organizationrequestingField;
            }
            set {
                this.organizationrequestingField = value;
                this.RaisePropertyChanged("organizationrequesting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
                this.RaisePropertyChanged("errorcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string errortext {
            get {
                return this.errortextField;
            }
            set {
                this.errortextField = value;
                this.RaisePropertyChanged("errortext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class Restrictions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string organizationinformationforwardingrestrictionsField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information-forwarding-restrictions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string organizationinformationforwardingrestrictions {
            get {
                return this.organizationinformationforwardingrestrictionsField;
            }
            set {
                this.organizationinformationforwardingrestrictionsField = value;
                this.RaisePropertyChanged("organizationinformationforwardingrestrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ntcip.org/c2c-message-administration")]
    public partial class C2cMessageReceipt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string informationalTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string informationalText {
            get {
                return this.informationalTextField;
            }
            set {
                this.informationalTextField = value;
                this.RaisePropertyChanged("informationalText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class PlanSignalInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signaltimingmodeField;
        
        private byte cyclelengthField;
        
        private string timingpatternidField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("signal-timing-mode", Order=0)]
        public string signaltimingmode {
            get {
                return this.signaltimingmodeField;
            }
            set {
                this.signaltimingmodeField = value;
                this.RaisePropertyChanged("signaltimingmode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cycle-length", Order=1)]
        public byte cyclelength {
            get {
                return this.cyclelengthField;
            }
            set {
                this.cyclelengthField = value;
                this.RaisePropertyChanged("cyclelength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("timing-pattern-id", Order=2)]
        public string timingpatternid {
            get {
                return this.timingpatternidField;
            }
            set {
                this.timingpatternidField = value;
                this.RaisePropertyChanged("timingpatternid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class PlanRampMeterInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string meterimplementedactionField;
        
        private byte meterimplementedplanField;
        
        private ushort meterimplementedrateField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("meter-implemented-action", Order=0)]
        public string meterimplementedaction {
            get {
                return this.meterimplementedactionField;
            }
            set {
                this.meterimplementedactionField = value;
                this.RaisePropertyChanged("meterimplementedaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("meter-implemented-plan", Order=1)]
        public byte meterimplementedplan {
            get {
                return this.meterimplementedplanField;
            }
            set {
                this.meterimplementedplanField = value;
                this.RaisePropertyChanged("meterimplementedplan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("meter-implemented-rate", Order=2)]
        public ushort meterimplementedrate {
            get {
                return this.meterimplementedrateField;
            }
            set {
                this.meterimplementedrateField = value;
                this.RaisePropertyChanged("meterimplementedrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class PlanLCSInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte controlledlanenumberField;
        
        private string lanecurrentstateField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("controlled-lane-number", Order=0)]
        public byte controlledlanenumber {
            get {
                return this.controlledlanenumberField;
            }
            set {
                this.controlledlanenumberField = value;
                this.RaisePropertyChanged("controlledlanenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lane-current-state", Order=1)]
        public string lanecurrentstate {
            get {
                return this.lanecurrentstateField;
            }
            set {
                this.lanecurrentstateField = value;
                this.RaisePropertyChanged("lanecurrentstate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class PlanGateInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gatestatusField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gate-status", Order=0)]
        public string gatestatus {
            get {
                return this.gatestatusField;
            }
            set {
                this.gatestatusField = value;
                this.RaisePropertyChanged("gatestatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class PlanDMSInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dmssigntypeField;
        
        private string dmsmessageField;
        
        private byte messagenumberField;
        
        private byte messagebeaconField;
        
        private string messagebeacontypeField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dms-sign-type", Order=0)]
        public string dmssigntype {
            get {
                return this.dmssigntypeField;
            }
            set {
                this.dmssigntypeField = value;
                this.RaisePropertyChanged("dmssigntype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dms-message", Order=1)]
        public string dmsmessage {
            get {
                return this.dmsmessageField;
            }
            set {
                this.dmsmessageField = value;
                this.RaisePropertyChanged("dmsmessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-number", Order=2)]
        public byte messagenumber {
            get {
                return this.messagenumberField;
            }
            set {
                this.messagenumberField = value;
                this.RaisePropertyChanged("messagenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-beacon", Order=3)]
        public byte messagebeacon {
            get {
                return this.messagebeaconField;
            }
            set {
                this.messagebeaconField = value;
                this.RaisePropertyChanged("messagebeacon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-beacon-type", Order=4)]
        public string messagebeacontype {
            get {
                return this.messagebeacontypeField;
            }
            set {
                this.messagebeacontypeField = value;
                this.RaisePropertyChanged("messagebeacontype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class PlanDevice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceidField;
        
        private string devicetypeField;
        
        private GeoLocation devicelocationField;
        
        private string devicenameField;
        
        private string devicedescriptionField;
        
        private string linkidField;
        
        private string linkdirectionField;
        
        private PlanDMSInfo dmsinformationField;
        
        private PlanGateInfo gateinformationField;
        
        private PlanLCSInfo lcsinformationField;
        
        private PlanRampMeterInfo rampmeterinformationField;
        
        private PlanSignalInfo signalinformationField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-id", Order=0)]
        public string deviceid {
            get {
                return this.deviceidField;
            }
            set {
                this.deviceidField = value;
                this.RaisePropertyChanged("deviceid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-type", Order=1)]
        public string devicetype {
            get {
                return this.devicetypeField;
            }
            set {
                this.devicetypeField = value;
                this.RaisePropertyChanged("devicetype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-location", Order=2)]
        public GeoLocation devicelocation {
            get {
                return this.devicelocationField;
            }
            set {
                this.devicelocationField = value;
                this.RaisePropertyChanged("devicelocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-name", Order=3)]
        public string devicename {
            get {
                return this.devicenameField;
            }
            set {
                this.devicenameField = value;
                this.RaisePropertyChanged("devicename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-description", Order=4)]
        public string devicedescription {
            get {
                return this.devicedescriptionField;
            }
            set {
                this.devicedescriptionField = value;
                this.RaisePropertyChanged("devicedescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link-id", Order=5)]
        public string linkid {
            get {
                return this.linkidField;
            }
            set {
                this.linkidField = value;
                this.RaisePropertyChanged("linkid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link-direction", Order=6)]
        public string linkdirection {
            get {
                return this.linkdirectionField;
            }
            set {
                this.linkdirectionField = value;
                this.RaisePropertyChanged("linkdirection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dms-information", Order=7)]
        public PlanDMSInfo dmsinformation {
            get {
                return this.dmsinformationField;
            }
            set {
                this.dmsinformationField = value;
                this.RaisePropertyChanged("dmsinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gate-information", Order=8)]
        public PlanGateInfo gateinformation {
            get {
                return this.gateinformationField;
            }
            set {
                this.gateinformationField = value;
                this.RaisePropertyChanged("gateinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lcs-information", Order=9)]
        public PlanLCSInfo lcsinformation {
            get {
                return this.lcsinformationField;
            }
            set {
                this.lcsinformationField = value;
                this.RaisePropertyChanged("lcsinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ramp-meter-information", Order=10)]
        public PlanRampMeterInfo rampmeterinformation {
            get {
                return this.rampmeterinformationField;
            }
            set {
                this.rampmeterinformationField = value;
                this.RaisePropertyChanged("rampmeterinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("signal-information", Order=11)]
        public PlanSignalInfo signalinformation {
            get {
                return this.signalinformationField;
            }
            set {
                this.signalinformationField = value;
                this.RaisePropertyChanged("signalinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=12)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class GeoLocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int latitudeField;
        
        private int longitudeField;
        
        private string horizontalDatumField;
        
        private Height heightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string horizontalDatum {
            get {
                return this.horizontalDatumField;
            }
            set {
                this.horizontalDatumField = value;
                this.RaisePropertyChanged("horizontalDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Height height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class Height : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("altitude", typeof(Distance), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("verticalDatum", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("verticalLevel", typeof(sbyte), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class Distance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("blkDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("block", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dm", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ft", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ftDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("in", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("inDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("km", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("kmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("m", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mi", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("miDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mm", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("yd", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ydDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":blkDec")]
        blkDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":block")]
        block,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":dm")]
        dm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":dmDec")]
        dmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ft")]
        ft,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ftDec")]
        ftDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":in")]
        @in,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":inDec")]
        inDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":km")]
        km,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":kmDec")]
        kmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":m")]
        m,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mDec")]
        mDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mi")]
        mi,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":miDec")]
        miDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mm")]
        mm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mmDec")]
        mmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":yd")]
        yd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ydDec")]
        ydDec,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DateTimeZone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private string timeField;
        
        private string offsetField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationCenterInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string centeridField;
        
        private string centernameField;
        
        private GeoLocation centerlocationField;
        
        private string centerdescriptionField;
        
        private string centertypeField;
        
        private ContactDetails centercontactdetailsField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string centerid {
            get {
                return this.centeridField;
            }
            set {
                this.centeridField = value;
                this.RaisePropertyChanged("centerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string centername {
            get {
                return this.centernameField;
            }
            set {
                this.centernameField = value;
                this.RaisePropertyChanged("centername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public GeoLocation centerlocation {
            get {
                return this.centerlocationField;
            }
            set {
                this.centerlocationField = value;
                this.RaisePropertyChanged("centerlocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string centerdescription {
            get {
                return this.centerdescriptionField;
            }
            set {
                this.centerdescriptionField = value;
                this.RaisePropertyChanged("centerdescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string centertype {
            get {
                return this.centertypeField;
            }
            set {
                this.centertypeField = value;
                this.RaisePropertyChanged("centertype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ContactDetails centercontactdetails {
            get {
                return this.centercontactdetailsField;
            }
            set {
                this.centercontactdetailsField = value;
                this.RaisePropertyChanged("centercontactdetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class ContactDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contactidField;
        
        private string personnameField;
        
        private string persontitleField;
        
        private string phonenumberField;
        
        private string phonealternateField;
        
        private string mobilephonenumberField;
        
        private string mobilephoneidField;
        
        private string faxnumberField;
        
        private string pagernumberField;
        
        private string pageridField;
        
        private string emailaddressField;
        
        private string radiounitField;
        
        private string addressline1Field;
        
        private string addressline2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipcodeField;
        
        private string countryField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contact-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contactid {
            get {
                return this.contactidField;
            }
            set {
                this.contactidField = value;
                this.RaisePropertyChanged("contactid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("person-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string personname {
            get {
                return this.personnameField;
            }
            set {
                this.personnameField = value;
                this.RaisePropertyChanged("personname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("person-title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string persontitle {
            get {
                return this.persontitleField;
            }
            set {
                this.persontitleField = value;
                this.RaisePropertyChanged("persontitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string phonenumber {
            get {
                return this.phonenumberField;
            }
            set {
                this.phonenumberField = value;
                this.RaisePropertyChanged("phonenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-alternate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string phonealternate {
            get {
                return this.phonealternateField;
            }
            set {
                this.phonealternateField = value;
                this.RaisePropertyChanged("phonealternate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mobile-phone-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string mobilephonenumber {
            get {
                return this.mobilephonenumberField;
            }
            set {
                this.mobilephonenumberField = value;
                this.RaisePropertyChanged("mobilephonenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mobile-phone-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string mobilephoneid {
            get {
                return this.mobilephoneidField;
            }
            set {
                this.mobilephoneidField = value;
                this.RaisePropertyChanged("mobilephoneid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fax-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string faxnumber {
            get {
                return this.faxnumberField;
            }
            set {
                this.faxnumberField = value;
                this.RaisePropertyChanged("faxnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pager-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string pagernumber {
            get {
                return this.pagernumberField;
            }
            set {
                this.pagernumberField = value;
                this.RaisePropertyChanged("pagernumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pager-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string pagerid {
            get {
                return this.pageridField;
            }
            set {
                this.pageridField = value;
                this.RaisePropertyChanged("pagerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email-address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string emailaddress {
            get {
                return this.emailaddressField;
            }
            set {
                this.emailaddressField = value;
                this.RaisePropertyChanged("emailaddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("radio-unit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string radiounit {
            get {
                return this.radiounitField;
            }
            set {
                this.radiounitField = value;
                this.RaisePropertyChanged("radiounit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address-line1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string addressline1 {
            get {
                return this.addressline1Field;
            }
            set {
                this.addressline1Field = value;
                this.RaisePropertyChanged("addressline1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address-line2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string addressline2 {
            get {
                return this.addressline2Field;
            }
            set {
                this.addressline2Field = value;
                this.RaisePropertyChanged("addressline2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zip-code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
                this.RaisePropertyChanged("zipcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=18)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string organizationidField;
        
        private string organizationnameField;
        
        private string organizationlocationField;
        
        private string organizationfunctionField;
        
        private ContactDetails organizationcontactdetailsField;
        
        private OrganizationInformationCentercontactlist centercontactlistField;
        
        private DateTimeZone lastupdatetimeField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string organizationid {
            get {
                return this.organizationidField;
            }
            set {
                this.organizationidField = value;
                this.RaisePropertyChanged("organizationid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string organizationname {
            get {
                return this.organizationnameField;
            }
            set {
                this.organizationnameField = value;
                this.RaisePropertyChanged("organizationname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string organizationlocation {
            get {
                return this.organizationlocationField;
            }
            set {
                this.organizationlocationField = value;
                this.RaisePropertyChanged("organizationlocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-function", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string organizationfunction {
            get {
                return this.organizationfunctionField;
            }
            set {
                this.organizationfunctionField = value;
                this.RaisePropertyChanged("organizationfunction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ContactDetails organizationcontactdetails {
            get {
                return this.organizationcontactdetailsField;
            }
            set {
                this.organizationcontactdetailsField = value;
                this.RaisePropertyChanged("organizationcontactdetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public OrganizationInformationCentercontactlist centercontactlist {
            get {
                return this.centercontactlistField;
            }
            set {
                this.centercontactlistField = value;
                this.RaisePropertyChanged("centercontactlist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-update-time", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public DateTimeZone lastupdatetime {
            get {
                return this.lastupdatetimeField;
            }
            set {
                this.lastupdatetimeField = value;
                this.RaisePropertyChanged("lastupdatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=7)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationInformationCentercontactlist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrganizationCenterInformation[] centercontactdetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OrganizationCenterInformation[] centercontactdetails {
            get {
                return this.centercontactdetailsField;
            }
            set {
                this.centercontactdetailsField = value;
                this.RaisePropertyChanged("centercontactdetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class PlanInventoryHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrganizationInformation organizationinformationField;
        
        private string planidField;
        
        private string plandescriptionField;
        
        private string plantypeField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information", Order=0)]
        public OrganizationInformation organizationinformation {
            get {
                return this.organizationinformationField;
            }
            set {
                this.organizationinformationField = value;
                this.RaisePropertyChanged("organizationinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plan-id", Order=1)]
        public string planid {
            get {
                return this.planidField;
            }
            set {
                this.planidField = value;
                this.RaisePropertyChanged("planid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plan-description", Order=2)]
        public string plandescription {
            get {
                return this.plandescriptionField;
            }
            set {
                this.plandescriptionField = value;
                this.RaisePropertyChanged("plandescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plan-type", Order=3)]
        public string plantype {
            get {
                return this.plantypeField;
            }
            set {
                this.plantypeField = value;
                this.RaisePropertyChanged("plantype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class PlanInventory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PlanInventoryHeader planinventoryheaderField;
        
        private PlanDevice[] deviceField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plan-inventory-header", Order=0)]
        public PlanInventoryHeader planinventoryheader {
            get {
                return this.planinventoryheaderField;
            }
            set {
                this.planinventoryheaderField = value;
                this.RaisePropertyChanged("planinventoryheader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device", Order=1)]
        public PlanDevice[] device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
                this.RaisePropertyChanged("device");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/transport_network/TransportInfras" +
        "tructureAsset_v0", ConfigurationName="TMCTransportInfrastructureAsset.TransportInfrastructureAssetPortType_v0p1")]
    public interface TransportInfrastructureAssetPortType_v0p1 {
        
        // CODEGEN: Generating message contract since the operation publishPlanInventory is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:PegaRULES:SOAP:Device:Services#PublishPlanInventory", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(C2CServer.TMCTransportInfrastructureAsset.errorReport), Action="urn:PegaRULES:SOAP:Device:Services#PublishPlanInventory", Name="errorReport", Namespace="http://transport.nsw.gov.au/tmc/services/entity/transport_network/TransportInfras" +
            "tructureAsset_v0p1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryResponse1 publishPlanInventory(C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:PegaRULES:SOAP:Device:Services#PublishPlanInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryResponse1> publishPlanInventoryAsync(C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
    public partial class MsgContextCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgSolutionField;
        
        private string msgCorrelationIDField;
        
        private string msgTransactionField;
        
        private string msgSourceField;
        
        private string msgDestinationField;
        
        private string msgPriorityField;
        
        private System.DateTime msgTimestampField;
        
        private bool msgTimestampFieldSpecified;
        
        private ExtensionCType[] extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string msgSolution {
            get {
                return this.msgSolutionField;
            }
            set {
                this.msgSolutionField = value;
                this.RaisePropertyChanged("msgSolution");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string msgCorrelationID {
            get {
                return this.msgCorrelationIDField;
            }
            set {
                this.msgCorrelationIDField = value;
                this.RaisePropertyChanged("msgCorrelationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msgTransaction {
            get {
                return this.msgTransactionField;
            }
            set {
                this.msgTransactionField = value;
                this.RaisePropertyChanged("msgTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string msgSource {
            get {
                return this.msgSourceField;
            }
            set {
                this.msgSourceField = value;
                this.RaisePropertyChanged("msgSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string msgDestination {
            get {
                return this.msgDestinationField;
            }
            set {
                this.msgDestinationField = value;
                this.RaisePropertyChanged("msgDestination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=5)]
        public string msgPriority {
            get {
                return this.msgPriorityField;
            }
            set {
                this.msgPriorityField = value;
                this.RaisePropertyChanged("msgPriority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime msgTimestamp {
            get {
                return this.msgTimestampField;
            }
            set {
                this.msgTimestampField = value;
                this.RaisePropertyChanged("msgTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msgTimestampSpecified {
            get {
                return this.msgTimestampFieldSpecified;
            }
            set {
                this.msgTimestampFieldSpecified = value;
                this.RaisePropertyChanged("msgTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ExtensionCType[] extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
    public partial class ExtensionCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/transport_network/TransportInfras" +
        "tructureAsset_v0p1")]
    public partial class publishPlanInventory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private planInventoryMsg planInventoryMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tmdd.org/3/messages", Order=0)]
        public planInventoryMsg planInventoryMsg {
            get {
                return this.planInventoryMsgField;
            }
            set {
                this.planInventoryMsgField = value;
                this.RaisePropertyChanged("planInventoryMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class planInventoryMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PlanInventory[] planinventoryitemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plan-inventory-item", Order=0)]
        public PlanInventory[] planinventoryitem {
            get {
                return this.planinventoryitemField;
            }
            set {
                this.planinventoryitemField = value;
                this.RaisePropertyChanged("planinventoryitem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/transport_network/TransportInfras" +
        "tructureAsset_v0p1")]
    public partial class publishPlanInventoryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private C2cMessageReceipt c2cMessageReceiptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ntcip.org/c2c-message-administration", Order=0)]
        public C2cMessageReceipt c2cMessageReceipt {
            get {
                return this.c2cMessageReceiptField;
            }
            set {
                this.c2cMessageReceiptField = value;
                this.RaisePropertyChanged("c2cMessageReceipt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishPlanInventoryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
        public C2CServer.TMCTransportInfrastructureAsset.MsgContextCType MsgContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/transport_network/TransportInfras" +
            "tructureAsset_v0p1", Order=0)]
        public C2CServer.TMCTransportInfrastructureAsset.publishPlanInventory publishPlanInventory;
        
        public publishPlanInventoryRequest() {
        }
        
        public publishPlanInventoryRequest(C2CServer.TMCTransportInfrastructureAsset.MsgContextCType MsgContext, C2CServer.TMCTransportInfrastructureAsset.publishPlanInventory publishPlanInventory) {
            this.MsgContext = MsgContext;
            this.publishPlanInventory = publishPlanInventory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishPlanInventoryResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
        public C2CServer.TMCTransportInfrastructureAsset.MsgContextCType MsgContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/transport_network/TransportInfras" +
            "tructureAsset_v0p1", Order=0)]
        public C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryResponse publishPlanInventoryResponse;
        
        public publishPlanInventoryResponse1() {
        }
        
        public publishPlanInventoryResponse1(C2CServer.TMCTransportInfrastructureAsset.MsgContextCType MsgContext, C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryResponse publishPlanInventoryResponse) {
            this.MsgContext = MsgContext;
            this.publishPlanInventoryResponse = publishPlanInventoryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransportInfrastructureAssetPortType_v0p1Channel : C2CServer.TMCTransportInfrastructureAsset.TransportInfrastructureAssetPortType_v0p1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransportInfrastructureAssetPortType_v0p1Client : System.ServiceModel.ClientBase<C2CServer.TMCTransportInfrastructureAsset.TransportInfrastructureAssetPortType_v0p1>, C2CServer.TMCTransportInfrastructureAsset.TransportInfrastructureAssetPortType_v0p1 {
        
        public TransportInfrastructureAssetPortType_v0p1Client() {
        }
        
        public TransportInfrastructureAssetPortType_v0p1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransportInfrastructureAssetPortType_v0p1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportInfrastructureAssetPortType_v0p1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportInfrastructureAssetPortType_v0p1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryResponse1 C2CServer.TMCTransportInfrastructureAsset.TransportInfrastructureAssetPortType_v0p1.publishPlanInventory(C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryRequest request) {
            return base.Channel.publishPlanInventory(request);
        }
        
        public C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryResponse publishPlanInventory(ref C2CServer.TMCTransportInfrastructureAsset.MsgContextCType MsgContext, C2CServer.TMCTransportInfrastructureAsset.publishPlanInventory publishPlanInventory1) {
            C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryRequest inValue = new C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryRequest();
            inValue.MsgContext = MsgContext;
            inValue.publishPlanInventory = publishPlanInventory1;
            C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryResponse1 retVal = ((C2CServer.TMCTransportInfrastructureAsset.TransportInfrastructureAssetPortType_v0p1)(this)).publishPlanInventory(inValue);
            MsgContext = retVal.MsgContext;
            return retVal.publishPlanInventoryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryResponse1> C2CServer.TMCTransportInfrastructureAsset.TransportInfrastructureAssetPortType_v0p1.publishPlanInventoryAsync(C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryRequest request) {
            return base.Channel.publishPlanInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryResponse1> publishPlanInventoryAsync(C2CServer.TMCTransportInfrastructureAsset.MsgContextCType MsgContext, C2CServer.TMCTransportInfrastructureAsset.publishPlanInventory publishPlanInventory) {
            C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryRequest inValue = new C2CServer.TMCTransportInfrastructureAsset.publishPlanInventoryRequest();
            inValue.MsgContext = MsgContext;
            inValue.publishPlanInventory = publishPlanInventory;
            return ((C2CServer.TMCTransportInfrastructureAsset.TransportInfrastructureAssetPortType_v0p1)(this)).publishPlanInventoryAsync(inValue);
        }
    }
}
