//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2CServer.TMCSensor {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Sensor_v0p1")]
    public partial class errorReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorReport errorReportMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tmdd.org/3/messages", Order=0)]
        public ErrorReport errorReportMsg {
            get {
                return this.errorReportMsgField;
            }
            set {
                this.errorReportMsgField = value;
                this.RaisePropertyChanged("errorReportMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class ErrorReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Restrictions restrictionsField;
        
        private OrganizationInformation organizationinformationField;
        
        private OrganizationInformation organizationrequestingField;
        
        private string errorcodeField;
        
        private string errortextField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Restrictions restrictions {
            get {
                return this.restrictionsField;
            }
            set {
                this.restrictionsField = value;
                this.RaisePropertyChanged("restrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public OrganizationInformation organizationinformation {
            get {
                return this.organizationinformationField;
            }
            set {
                this.organizationinformationField = value;
                this.RaisePropertyChanged("organizationinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-requesting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public OrganizationInformation organizationrequesting {
            get {
                return this.organizationrequestingField;
            }
            set {
                this.organizationrequestingField = value;
                this.RaisePropertyChanged("organizationrequesting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
                this.RaisePropertyChanged("errorcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string errortext {
            get {
                return this.errortextField;
            }
            set {
                this.errortextField = value;
                this.RaisePropertyChanged("errortext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class Restrictions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string organizationinformationforwardingrestrictionsField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information-forwarding-restrictions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string organizationinformationforwardingrestrictions {
            get {
                return this.organizationinformationforwardingrestrictionsField;
            }
            set {
                this.organizationinformationforwardingrestrictionsField = value;
                this.RaisePropertyChanged("organizationinformationforwardingrestrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ntcip.org/c2c-message-administration")]
    public partial class C2cMessageReceipt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string informationalTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string informationalText {
            get {
                return this.informationalTextField;
            }
            set {
                this.informationalTextField = value;
                this.RaisePropertyChanged("informationalText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DetectorDataDetail))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DetectorDataDetail_TMDD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stationidField;
        
        private string detectoridField;
        
        private DateTimeZone detectiontimestampField;
        
        private uint vehiclecountField;
        
        private byte vehicleoccupancyField;
        
        private DateTimeZone starttimeField;
        
        private DateTimeZone endtimeField;
        
        private string detectordatatypeField;
        
        private byte vehiclespeedField;
        
        private bool vehiclespeedFieldSpecified;
        
        private uint queuelengthField;
        
        private bool queuelengthFieldSpecified;
        
        private uint vehiclestopsField;
        
        private bool vehiclestopsFieldSpecified;
        
        private uint vehiclecountbin1Field;
        
        private bool vehiclecountbin1FieldSpecified;
        
        private uint vehiclecountbin2Field;
        
        private bool vehiclecountbin2FieldSpecified;
        
        private uint vehiclecountbin3Field;
        
        private bool vehiclecountbin3FieldSpecified;
        
        private uint vehiclecountbin4Field;
        
        private bool vehiclecountbin4FieldSpecified;
        
        private uint vehiclecountbin5Field;
        
        private bool vehiclecountbin5FieldSpecified;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("station-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string stationid {
            get {
                return this.stationidField;
            }
            set {
                this.stationidField = value;
                this.RaisePropertyChanged("stationid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string detectorid {
            get {
                return this.detectoridField;
            }
            set {
                this.detectoridField = value;
                this.RaisePropertyChanged("detectorid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detection-time-stamp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DateTimeZone detectiontimestamp {
            get {
                return this.detectiontimestampField;
            }
            set {
                this.detectiontimestampField = value;
                this.RaisePropertyChanged("detectiontimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle-count", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public uint vehiclecount {
            get {
                return this.vehiclecountField;
            }
            set {
                this.vehiclecountField = value;
                this.RaisePropertyChanged("vehiclecount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle-occupancy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public byte vehicleoccupancy {
            get {
                return this.vehicleoccupancyField;
            }
            set {
                this.vehicleoccupancyField = value;
                this.RaisePropertyChanged("vehicleoccupancy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("start-time", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public DateTimeZone starttime {
            get {
                return this.starttimeField;
            }
            set {
                this.starttimeField = value;
                this.RaisePropertyChanged("starttime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("end-time", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public DateTimeZone endtime {
            get {
                return this.endtimeField;
            }
            set {
                this.endtimeField = value;
                this.RaisePropertyChanged("endtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector-data-type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string detectordatatype {
            get {
                return this.detectordatatypeField;
            }
            set {
                this.detectordatatypeField = value;
                this.RaisePropertyChanged("detectordatatype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle-speed", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public byte vehiclespeed {
            get {
                return this.vehiclespeedField;
            }
            set {
                this.vehiclespeedField = value;
                this.RaisePropertyChanged("vehiclespeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vehiclespeedSpecified {
            get {
                return this.vehiclespeedFieldSpecified;
            }
            set {
                this.vehiclespeedFieldSpecified = value;
                this.RaisePropertyChanged("vehiclespeedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("queue-length", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public uint queuelength {
            get {
                return this.queuelengthField;
            }
            set {
                this.queuelengthField = value;
                this.RaisePropertyChanged("queuelength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool queuelengthSpecified {
            get {
                return this.queuelengthFieldSpecified;
            }
            set {
                this.queuelengthFieldSpecified = value;
                this.RaisePropertyChanged("queuelengthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle-stops", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public uint vehiclestops {
            get {
                return this.vehiclestopsField;
            }
            set {
                this.vehiclestopsField = value;
                this.RaisePropertyChanged("vehiclestops");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vehiclestopsSpecified {
            get {
                return this.vehiclestopsFieldSpecified;
            }
            set {
                this.vehiclestopsFieldSpecified = value;
                this.RaisePropertyChanged("vehiclestopsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle-count-bin1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public uint vehiclecountbin1 {
            get {
                return this.vehiclecountbin1Field;
            }
            set {
                this.vehiclecountbin1Field = value;
                this.RaisePropertyChanged("vehiclecountbin1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vehiclecountbin1Specified {
            get {
                return this.vehiclecountbin1FieldSpecified;
            }
            set {
                this.vehiclecountbin1FieldSpecified = value;
                this.RaisePropertyChanged("vehiclecountbin1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle-count-bin2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public uint vehiclecountbin2 {
            get {
                return this.vehiclecountbin2Field;
            }
            set {
                this.vehiclecountbin2Field = value;
                this.RaisePropertyChanged("vehiclecountbin2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vehiclecountbin2Specified {
            get {
                return this.vehiclecountbin2FieldSpecified;
            }
            set {
                this.vehiclecountbin2FieldSpecified = value;
                this.RaisePropertyChanged("vehiclecountbin2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle-count-bin3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public uint vehiclecountbin3 {
            get {
                return this.vehiclecountbin3Field;
            }
            set {
                this.vehiclecountbin3Field = value;
                this.RaisePropertyChanged("vehiclecountbin3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vehiclecountbin3Specified {
            get {
                return this.vehiclecountbin3FieldSpecified;
            }
            set {
                this.vehiclecountbin3FieldSpecified = value;
                this.RaisePropertyChanged("vehiclecountbin3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle-count-bin4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public uint vehiclecountbin4 {
            get {
                return this.vehiclecountbin4Field;
            }
            set {
                this.vehiclecountbin4Field = value;
                this.RaisePropertyChanged("vehiclecountbin4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vehiclecountbin4Specified {
            get {
                return this.vehiclecountbin4FieldSpecified;
            }
            set {
                this.vehiclecountbin4FieldSpecified = value;
                this.RaisePropertyChanged("vehiclecountbin4Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle-count-bin5", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public uint vehiclecountbin5 {
            get {
                return this.vehiclecountbin5Field;
            }
            set {
                this.vehiclecountbin5Field = value;
                this.RaisePropertyChanged("vehiclecountbin5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vehiclecountbin5Specified {
            get {
                return this.vehiclecountbin5FieldSpecified;
            }
            set {
                this.vehiclecountbin5FieldSpecified = value;
                this.RaisePropertyChanged("vehiclecountbin5Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=16)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DateTimeZone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private string timeField;
        
        private string offsetField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DetectorDataDetail : DetectorDataDetail_TMDD {
        
        private string suspectdataflagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("suspect-data-flag", Order=0)]
        public string suspectdataflag {
            get {
                return this.suspectdataflagField;
            }
            set {
                this.suspectdataflagField = value;
                this.RaisePropertyChanged("suspectdataflag");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class Distance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("blkDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("block", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dm", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ft", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ftDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("in", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("inDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("km", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("kmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("m", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mi", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("miDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mm", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("yd", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ydDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":blkDec")]
        blkDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":block")]
        block,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":dm")]
        dm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":dmDec")]
        dmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ft")]
        ft,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ftDec")]
        ftDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":in")]
        @in,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":inDec")]
        inDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":km")]
        km,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":kmDec")]
        kmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":m")]
        m,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mDec")]
        mDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mi")]
        mi,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":miDec")]
        miDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mm")]
        mm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mmDec")]
        mmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":yd")]
        yd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ydDec")]
        ydDec,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class Height : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("altitude", typeof(Distance), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("verticalDatum", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("verticalLevel", typeof(sbyte), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class GeoLocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int latitudeField;
        
        private int longitudeField;
        
        private string horizontalDatumField;
        
        private Height heightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string horizontalDatum {
            get {
                return this.horizontalDatumField;
            }
            set {
                this.horizontalDatumField = value;
                this.RaisePropertyChanged("horizontalDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Height height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationCenterInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string centeridField;
        
        private string centernameField;
        
        private GeoLocation centerlocationField;
        
        private string centerdescriptionField;
        
        private string centertypeField;
        
        private ContactDetails centercontactdetailsField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string centerid {
            get {
                return this.centeridField;
            }
            set {
                this.centeridField = value;
                this.RaisePropertyChanged("centerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string centername {
            get {
                return this.centernameField;
            }
            set {
                this.centernameField = value;
                this.RaisePropertyChanged("centername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public GeoLocation centerlocation {
            get {
                return this.centerlocationField;
            }
            set {
                this.centerlocationField = value;
                this.RaisePropertyChanged("centerlocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string centerdescription {
            get {
                return this.centerdescriptionField;
            }
            set {
                this.centerdescriptionField = value;
                this.RaisePropertyChanged("centerdescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string centertype {
            get {
                return this.centertypeField;
            }
            set {
                this.centertypeField = value;
                this.RaisePropertyChanged("centertype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ContactDetails centercontactdetails {
            get {
                return this.centercontactdetailsField;
            }
            set {
                this.centercontactdetailsField = value;
                this.RaisePropertyChanged("centercontactdetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class ContactDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contactidField;
        
        private string personnameField;
        
        private string persontitleField;
        
        private string phonenumberField;
        
        private string phonealternateField;
        
        private string mobilephonenumberField;
        
        private string mobilephoneidField;
        
        private string faxnumberField;
        
        private string pagernumberField;
        
        private string pageridField;
        
        private string emailaddressField;
        
        private string radiounitField;
        
        private string addressline1Field;
        
        private string addressline2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipcodeField;
        
        private string countryField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contact-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contactid {
            get {
                return this.contactidField;
            }
            set {
                this.contactidField = value;
                this.RaisePropertyChanged("contactid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("person-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string personname {
            get {
                return this.personnameField;
            }
            set {
                this.personnameField = value;
                this.RaisePropertyChanged("personname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("person-title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string persontitle {
            get {
                return this.persontitleField;
            }
            set {
                this.persontitleField = value;
                this.RaisePropertyChanged("persontitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string phonenumber {
            get {
                return this.phonenumberField;
            }
            set {
                this.phonenumberField = value;
                this.RaisePropertyChanged("phonenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-alternate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string phonealternate {
            get {
                return this.phonealternateField;
            }
            set {
                this.phonealternateField = value;
                this.RaisePropertyChanged("phonealternate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mobile-phone-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string mobilephonenumber {
            get {
                return this.mobilephonenumberField;
            }
            set {
                this.mobilephonenumberField = value;
                this.RaisePropertyChanged("mobilephonenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mobile-phone-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string mobilephoneid {
            get {
                return this.mobilephoneidField;
            }
            set {
                this.mobilephoneidField = value;
                this.RaisePropertyChanged("mobilephoneid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fax-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string faxnumber {
            get {
                return this.faxnumberField;
            }
            set {
                this.faxnumberField = value;
                this.RaisePropertyChanged("faxnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pager-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string pagernumber {
            get {
                return this.pagernumberField;
            }
            set {
                this.pagernumberField = value;
                this.RaisePropertyChanged("pagernumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pager-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string pagerid {
            get {
                return this.pageridField;
            }
            set {
                this.pageridField = value;
                this.RaisePropertyChanged("pagerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email-address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string emailaddress {
            get {
                return this.emailaddressField;
            }
            set {
                this.emailaddressField = value;
                this.RaisePropertyChanged("emailaddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("radio-unit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string radiounit {
            get {
                return this.radiounitField;
            }
            set {
                this.radiounitField = value;
                this.RaisePropertyChanged("radiounit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address-line1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string addressline1 {
            get {
                return this.addressline1Field;
            }
            set {
                this.addressline1Field = value;
                this.RaisePropertyChanged("addressline1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address-line2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string addressline2 {
            get {
                return this.addressline2Field;
            }
            set {
                this.addressline2Field = value;
                this.RaisePropertyChanged("addressline2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zip-code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
                this.RaisePropertyChanged("zipcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=18)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string organizationidField;
        
        private string organizationnameField;
        
        private string organizationlocationField;
        
        private string organizationfunctionField;
        
        private ContactDetails organizationcontactdetailsField;
        
        private OrganizationInformationCentercontactlist centercontactlistField;
        
        private DateTimeZone lastupdatetimeField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string organizationid {
            get {
                return this.organizationidField;
            }
            set {
                this.organizationidField = value;
                this.RaisePropertyChanged("organizationid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string organizationname {
            get {
                return this.organizationnameField;
            }
            set {
                this.organizationnameField = value;
                this.RaisePropertyChanged("organizationname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string organizationlocation {
            get {
                return this.organizationlocationField;
            }
            set {
                this.organizationlocationField = value;
                this.RaisePropertyChanged("organizationlocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-function", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string organizationfunction {
            get {
                return this.organizationfunctionField;
            }
            set {
                this.organizationfunctionField = value;
                this.RaisePropertyChanged("organizationfunction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ContactDetails organizationcontactdetails {
            get {
                return this.organizationcontactdetailsField;
            }
            set {
                this.organizationcontactdetailsField = value;
                this.RaisePropertyChanged("organizationcontactdetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public OrganizationInformationCentercontactlist centercontactlist {
            get {
                return this.centercontactlistField;
            }
            set {
                this.centercontactlistField = value;
                this.RaisePropertyChanged("centercontactlist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-update-time", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public DateTimeZone lastupdatetime {
            get {
                return this.lastupdatetimeField;
            }
            set {
                this.lastupdatetimeField = value;
                this.RaisePropertyChanged("lastupdatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=7)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationInformationCentercontactlist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrganizationCenterInformation[] centercontactdetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OrganizationCenterInformation[] centercontactdetails {
            get {
                return this.centercontactdetailsField;
            }
            set {
                this.centercontactdetailsField = value;
                this.RaisePropertyChanged("centercontactdetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DetectorData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Restrictions restrictionsField;
        
        private OrganizationInformation organizationinformationField;
        
        private DetectorDataDetectorlist detectorlistField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Restrictions restrictions {
            get {
                return this.restrictionsField;
            }
            set {
                this.restrictionsField = value;
                this.RaisePropertyChanged("restrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public OrganizationInformation organizationinformation {
            get {
                return this.organizationinformationField;
            }
            set {
                this.organizationinformationField = value;
                this.RaisePropertyChanged("organizationinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector-list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DetectorDataDetectorlist detectorlist {
            get {
                return this.detectorlistField;
            }
            set {
                this.detectorlistField = value;
                this.RaisePropertyChanged("detectorlist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class DetectorDataDetectorlist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DetectorDataDetail[] detectordatadetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector-data-detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DetectorDataDetail[] detectordatadetail {
            get {
                return this.detectordatadetailField;
            }
            set {
                this.detectordatadetailField = value;
                this.RaisePropertyChanged("detectordatadetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Sensor_v0", ConfigurationName="TMCSensor.SensorPortType_v0p1")]
    public interface SensorPortType_v0p1 {
        
        // CODEGEN: Generating message contract since the operation publishDetectorData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:PegaRULES:SOAP:Sensor:Services#PublishDetectorData", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(C2CServer.TMCSensor.errorReport), Action="urn:PegaRULES:SOAP:Sensor:Services#PublishDetectorData", Name="errorReport", Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Sensor_v0p1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DetectorDataDetail_TMDD))]
        C2CServer.TMCSensor.publishDetectorDataResponse1 publishDetectorData(C2CServer.TMCSensor.publishDetectorDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:PegaRULES:SOAP:Sensor:Services#PublishDetectorData", ReplyAction="*")]
        System.Threading.Tasks.Task<C2CServer.TMCSensor.publishDetectorDataResponse1> publishDetectorDataAsync(C2CServer.TMCSensor.publishDetectorDataRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
    public partial class MsgContextCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgSolutionField;
        
        private string msgCorrelationIDField;
        
        private string msgTransactionField;
        
        private string msgSourceField;
        
        private string msgDestinationField;
        
        private string msgPriorityField;
        
        private System.DateTime msgTimestampField;
        
        private bool msgTimestampFieldSpecified;
        
        private ExtensionCType[] extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string msgSolution {
            get {
                return this.msgSolutionField;
            }
            set {
                this.msgSolutionField = value;
                this.RaisePropertyChanged("msgSolution");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string msgCorrelationID {
            get {
                return this.msgCorrelationIDField;
            }
            set {
                this.msgCorrelationIDField = value;
                this.RaisePropertyChanged("msgCorrelationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msgTransaction {
            get {
                return this.msgTransactionField;
            }
            set {
                this.msgTransactionField = value;
                this.RaisePropertyChanged("msgTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string msgSource {
            get {
                return this.msgSourceField;
            }
            set {
                this.msgSourceField = value;
                this.RaisePropertyChanged("msgSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string msgDestination {
            get {
                return this.msgDestinationField;
            }
            set {
                this.msgDestinationField = value;
                this.RaisePropertyChanged("msgDestination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=5)]
        public string msgPriority {
            get {
                return this.msgPriorityField;
            }
            set {
                this.msgPriorityField = value;
                this.RaisePropertyChanged("msgPriority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime msgTimestamp {
            get {
                return this.msgTimestampField;
            }
            set {
                this.msgTimestampField = value;
                this.RaisePropertyChanged("msgTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msgTimestampSpecified {
            get {
                return this.msgTimestampFieldSpecified;
            }
            set {
                this.msgTimestampFieldSpecified = value;
                this.RaisePropertyChanged("msgTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ExtensionCType[] extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
    public partial class ExtensionCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Sensor_v0p1")]
    public partial class publishDetectorData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private detectorDataMsg detectorDataMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tmdd.org/3/messages", Order=0)]
        public detectorDataMsg detectorDataMsg {
            get {
                return this.detectorDataMsgField;
            }
            set {
                this.detectorDataMsgField = value;
                this.RaisePropertyChanged("detectorDataMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class detectorDataMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DetectorData[] detectordataitemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector-data-item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DetectorData[] detectordataitem {
            get {
                return this.detectordataitemField;
            }
            set {
                this.detectordataitemField = value;
                this.RaisePropertyChanged("detectordataitem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Sensor_v0p1")]
    public partial class publishDetectorDataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private C2cMessageReceipt c2cMessageReceiptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ntcip.org/c2c-message-administration", Order=0)]
        public C2cMessageReceipt c2cMessageReceipt {
            get {
                return this.c2cMessageReceiptField;
            }
            set {
                this.c2cMessageReceiptField = value;
                this.RaisePropertyChanged("c2cMessageReceipt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishDetectorDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
        public C2CServer.TMCSensor.MsgContextCType MsgContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Sensor_v0p1", Order=0)]
        public C2CServer.TMCSensor.publishDetectorData publishDetectorData;
        
        public publishDetectorDataRequest() {
        }
        
        public publishDetectorDataRequest(C2CServer.TMCSensor.MsgContextCType MsgContext, C2CServer.TMCSensor.publishDetectorData publishDetectorData) {
            this.MsgContext = MsgContext;
            this.publishDetectorData = publishDetectorData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishDetectorDataResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
        public C2CServer.TMCSensor.MsgContextCType MsgContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Sensor_v0p1", Order=0)]
        public C2CServer.TMCSensor.publishDetectorDataResponse publishDetectorDataResponse;
        
        public publishDetectorDataResponse1() {
        }
        
        public publishDetectorDataResponse1(C2CServer.TMCSensor.MsgContextCType MsgContext, C2CServer.TMCSensor.publishDetectorDataResponse publishDetectorDataResponse) {
            this.MsgContext = MsgContext;
            this.publishDetectorDataResponse = publishDetectorDataResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SensorPortType_v0p1Channel : C2CServer.TMCSensor.SensorPortType_v0p1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SensorPortType_v0p1Client : System.ServiceModel.ClientBase<C2CServer.TMCSensor.SensorPortType_v0p1>, C2CServer.TMCSensor.SensorPortType_v0p1 {
        
        public SensorPortType_v0p1Client() {
        }
        
        public SensorPortType_v0p1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SensorPortType_v0p1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SensorPortType_v0p1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SensorPortType_v0p1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        C2CServer.TMCSensor.publishDetectorDataResponse1 C2CServer.TMCSensor.SensorPortType_v0p1.publishDetectorData(C2CServer.TMCSensor.publishDetectorDataRequest request) {
            return base.Channel.publishDetectorData(request);
        }
        
        public C2CServer.TMCSensor.publishDetectorDataResponse publishDetectorData(ref C2CServer.TMCSensor.MsgContextCType MsgContext, C2CServer.TMCSensor.publishDetectorData publishDetectorData1) {
            C2CServer.TMCSensor.publishDetectorDataRequest inValue = new C2CServer.TMCSensor.publishDetectorDataRequest();
            inValue.MsgContext = MsgContext;
            inValue.publishDetectorData = publishDetectorData1;
            C2CServer.TMCSensor.publishDetectorDataResponse1 retVal = ((C2CServer.TMCSensor.SensorPortType_v0p1)(this)).publishDetectorData(inValue);
            MsgContext = retVal.MsgContext;
            return retVal.publishDetectorDataResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<C2CServer.TMCSensor.publishDetectorDataResponse1> C2CServer.TMCSensor.SensorPortType_v0p1.publishDetectorDataAsync(C2CServer.TMCSensor.publishDetectorDataRequest request) {
            return base.Channel.publishDetectorDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<C2CServer.TMCSensor.publishDetectorDataResponse1> publishDetectorDataAsync(C2CServer.TMCSensor.MsgContextCType MsgContext, C2CServer.TMCSensor.publishDetectorData publishDetectorData) {
            C2CServer.TMCSensor.publishDetectorDataRequest inValue = new C2CServer.TMCSensor.publishDetectorDataRequest();
            inValue.MsgContext = MsgContext;
            inValue.publishDetectorData = publishDetectorData;
            return ((C2CServer.TMCSensor.SensorPortType_v0p1)(this)).publishDetectorDataAsync(inValue);
        }
    }
}
