//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2CServer.TransportDevice {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0p1")]
    public partial class errorReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorReport errorReportMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tmdd.org/3/messages", Order=0)]
        public ErrorReport errorReportMsg {
            get {
                return this.errorReportMsgField;
            }
            set {
                this.errorReportMsgField = value;
                this.RaisePropertyChanged("errorReportMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class ErrorReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Restrictions restrictionsField;
        
        private OrganizationInformation organizationinformationField;
        
        private OrganizationInformation organizationrequestingField;
        
        private string errorcodeField;
        
        private string errortextField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Restrictions restrictions {
            get {
                return this.restrictionsField;
            }
            set {
                this.restrictionsField = value;
                this.RaisePropertyChanged("restrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public OrganizationInformation organizationinformation {
            get {
                return this.organizationinformationField;
            }
            set {
                this.organizationinformationField = value;
                this.RaisePropertyChanged("organizationinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-requesting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public OrganizationInformation organizationrequesting {
            get {
                return this.organizationrequestingField;
            }
            set {
                this.organizationrequestingField = value;
                this.RaisePropertyChanged("organizationrequesting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
                this.RaisePropertyChanged("errorcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string errortext {
            get {
                return this.errortextField;
            }
            set {
                this.errortextField = value;
                this.RaisePropertyChanged("errortext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class Restrictions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string organizationinformationforwardingrestrictionsField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information-forwarding-restrictions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string organizationinformationforwardingrestrictions {
            get {
                return this.organizationinformationforwardingrestrictionsField;
            }
            set {
                this.organizationinformationforwardingrestrictionsField = value;
                this.RaisePropertyChanged("organizationinformationforwardingrestrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ntcip.org/c2c-message-administration")]
    public partial class C2cMessageReceipt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string informationalTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string informationalText {
            get {
                return this.informationalTextField;
            }
            set {
                this.informationalTextField = value;
                this.RaisePropertyChanged("informationalText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DetectorStatusDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DeviceStatusHeader detectorstatusheaderField;
        
        private byte detectorlanenumberField;
        
        private bool detectorlanenumberFieldSpecified;
        
        private string lanedirectionField;
        
        private byte detectoroutputmodeField;
        
        private bool detectoroutputmodeFieldSpecified;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector-status-header", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DeviceStatusHeader detectorstatusheader {
            get {
                return this.detectorstatusheaderField;
            }
            set {
                this.detectorstatusheaderField = value;
                this.RaisePropertyChanged("detectorstatusheader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector-lane-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public byte detectorlanenumber {
            get {
                return this.detectorlanenumberField;
            }
            set {
                this.detectorlanenumberField = value;
                this.RaisePropertyChanged("detectorlanenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool detectorlanenumberSpecified {
            get {
                return this.detectorlanenumberFieldSpecified;
            }
            set {
                this.detectorlanenumberFieldSpecified = value;
                this.RaisePropertyChanged("detectorlanenumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lane-direction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lanedirection {
            get {
                return this.lanedirectionField;
            }
            set {
                this.lanedirectionField = value;
                this.RaisePropertyChanged("lanedirection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector-outputmode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public byte detectoroutputmode {
            get {
                return this.detectoroutputmodeField;
            }
            set {
                this.detectoroutputmodeField = value;
                this.RaisePropertyChanged("detectoroutputmode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool detectoroutputmodeSpecified {
            get {
                return this.detectoroutputmodeFieldSpecified;
            }
            set {
                this.detectoroutputmodeFieldSpecified = value;
                this.RaisePropertyChanged("detectoroutputmodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DeviceStatusHeader : DeviceStatusHeader_TMDD {
        
        private string deviceerrorField;
        
        private string[] additionaldeviceerrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-error", Order=0)]
        public string deviceerror {
            get {
                return this.deviceerrorField;
            }
            set {
                this.deviceerrorField = value;
                this.RaisePropertyChanged("deviceerror");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additional-device-error", Order=1)]
        public string[] additionaldeviceerror {
            get {
                return this.additionaldeviceerrorField;
            }
            set {
                this.additionaldeviceerrorField = value;
                this.RaisePropertyChanged("additionaldeviceerror");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceStatusHeader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DeviceStatusHeader_TMDD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrganizationInformation organizationinformationField;
        
        private string deviceidField;
        
        private string devicestatusField;
        
        private string centeridField;
        
        private string devicecommstatusField;
        
        private string operatoridField;
        
        private string eventidField;
        
        private string responseplanidField;
        
        private DateTimeZone lastcommtimeField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OrganizationInformation organizationinformation {
            get {
                return this.organizationinformationField;
            }
            set {
                this.organizationinformationField = value;
                this.RaisePropertyChanged("organizationinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string deviceid {
            get {
                return this.deviceidField;
            }
            set {
                this.deviceidField = value;
                this.RaisePropertyChanged("deviceid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string devicestatus {
            get {
                return this.devicestatusField;
            }
            set {
                this.devicestatusField = value;
                this.RaisePropertyChanged("devicestatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string centerid {
            get {
                return this.centeridField;
            }
            set {
                this.centeridField = value;
                this.RaisePropertyChanged("centerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-comm-status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string devicecommstatus {
            get {
                return this.devicecommstatusField;
            }
            set {
                this.devicecommstatusField = value;
                this.RaisePropertyChanged("devicecommstatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("operator-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string operatorid {
            get {
                return this.operatoridField;
            }
            set {
                this.operatoridField = value;
                this.RaisePropertyChanged("operatorid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("event-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string eventid {
            get {
                return this.eventidField;
            }
            set {
                this.eventidField = value;
                this.RaisePropertyChanged("eventid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("response-plan-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string responseplanid {
            get {
                return this.responseplanidField;
            }
            set {
                this.responseplanidField = value;
                this.RaisePropertyChanged("responseplanid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-comm-time", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public DateTimeZone lastcommtime {
            get {
                return this.lastcommtimeField;
            }
            set {
                this.lastcommtimeField = value;
                this.RaisePropertyChanged("lastcommtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=9)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string organizationidField;
        
        private string organizationnameField;
        
        private string organizationlocationField;
        
        private string organizationfunctionField;
        
        private ContactDetails organizationcontactdetailsField;
        
        private OrganizationInformationCentercontactlist centercontactlistField;
        
        private DateTimeZone lastupdatetimeField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string organizationid {
            get {
                return this.organizationidField;
            }
            set {
                this.organizationidField = value;
                this.RaisePropertyChanged("organizationid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string organizationname {
            get {
                return this.organizationnameField;
            }
            set {
                this.organizationnameField = value;
                this.RaisePropertyChanged("organizationname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string organizationlocation {
            get {
                return this.organizationlocationField;
            }
            set {
                this.organizationlocationField = value;
                this.RaisePropertyChanged("organizationlocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-function", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string organizationfunction {
            get {
                return this.organizationfunctionField;
            }
            set {
                this.organizationfunctionField = value;
                this.RaisePropertyChanged("organizationfunction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ContactDetails organizationcontactdetails {
            get {
                return this.organizationcontactdetailsField;
            }
            set {
                this.organizationcontactdetailsField = value;
                this.RaisePropertyChanged("organizationcontactdetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public OrganizationInformationCentercontactlist centercontactlist {
            get {
                return this.centercontactlistField;
            }
            set {
                this.centercontactlistField = value;
                this.RaisePropertyChanged("centercontactlist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-update-time", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public DateTimeZone lastupdatetime {
            get {
                return this.lastupdatetimeField;
            }
            set {
                this.lastupdatetimeField = value;
                this.RaisePropertyChanged("lastupdatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=7)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class ContactDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contactidField;
        
        private string personnameField;
        
        private string persontitleField;
        
        private string phonenumberField;
        
        private string phonealternateField;
        
        private string mobilephonenumberField;
        
        private string mobilephoneidField;
        
        private string faxnumberField;
        
        private string pagernumberField;
        
        private string pageridField;
        
        private string emailaddressField;
        
        private string radiounitField;
        
        private string addressline1Field;
        
        private string addressline2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipcodeField;
        
        private string countryField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contact-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contactid {
            get {
                return this.contactidField;
            }
            set {
                this.contactidField = value;
                this.RaisePropertyChanged("contactid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("person-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string personname {
            get {
                return this.personnameField;
            }
            set {
                this.personnameField = value;
                this.RaisePropertyChanged("personname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("person-title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string persontitle {
            get {
                return this.persontitleField;
            }
            set {
                this.persontitleField = value;
                this.RaisePropertyChanged("persontitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string phonenumber {
            get {
                return this.phonenumberField;
            }
            set {
                this.phonenumberField = value;
                this.RaisePropertyChanged("phonenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-alternate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string phonealternate {
            get {
                return this.phonealternateField;
            }
            set {
                this.phonealternateField = value;
                this.RaisePropertyChanged("phonealternate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mobile-phone-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string mobilephonenumber {
            get {
                return this.mobilephonenumberField;
            }
            set {
                this.mobilephonenumberField = value;
                this.RaisePropertyChanged("mobilephonenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mobile-phone-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string mobilephoneid {
            get {
                return this.mobilephoneidField;
            }
            set {
                this.mobilephoneidField = value;
                this.RaisePropertyChanged("mobilephoneid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fax-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string faxnumber {
            get {
                return this.faxnumberField;
            }
            set {
                this.faxnumberField = value;
                this.RaisePropertyChanged("faxnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pager-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string pagernumber {
            get {
                return this.pagernumberField;
            }
            set {
                this.pagernumberField = value;
                this.RaisePropertyChanged("pagernumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pager-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string pagerid {
            get {
                return this.pageridField;
            }
            set {
                this.pageridField = value;
                this.RaisePropertyChanged("pagerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email-address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string emailaddress {
            get {
                return this.emailaddressField;
            }
            set {
                this.emailaddressField = value;
                this.RaisePropertyChanged("emailaddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("radio-unit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string radiounit {
            get {
                return this.radiounitField;
            }
            set {
                this.radiounitField = value;
                this.RaisePropertyChanged("radiounit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address-line1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string addressline1 {
            get {
                return this.addressline1Field;
            }
            set {
                this.addressline1Field = value;
                this.RaisePropertyChanged("addressline1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address-line2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string addressline2 {
            get {
                return this.addressline2Field;
            }
            set {
                this.addressline2Field = value;
                this.RaisePropertyChanged("addressline2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zip-code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
                this.RaisePropertyChanged("zipcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=18)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationInformationCentercontactlist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrganizationCenterInformation[] centercontactdetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OrganizationCenterInformation[] centercontactdetails {
            get {
                return this.centercontactdetailsField;
            }
            set {
                this.centercontactdetailsField = value;
                this.RaisePropertyChanged("centercontactdetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationCenterInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string centeridField;
        
        private string centernameField;
        
        private GeoLocation centerlocationField;
        
        private string centerdescriptionField;
        
        private string centertypeField;
        
        private ContactDetails centercontactdetailsField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string centerid {
            get {
                return this.centeridField;
            }
            set {
                this.centeridField = value;
                this.RaisePropertyChanged("centerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string centername {
            get {
                return this.centernameField;
            }
            set {
                this.centernameField = value;
                this.RaisePropertyChanged("centername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public GeoLocation centerlocation {
            get {
                return this.centerlocationField;
            }
            set {
                this.centerlocationField = value;
                this.RaisePropertyChanged("centerlocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string centerdescription {
            get {
                return this.centerdescriptionField;
            }
            set {
                this.centerdescriptionField = value;
                this.RaisePropertyChanged("centerdescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string centertype {
            get {
                return this.centertypeField;
            }
            set {
                this.centertypeField = value;
                this.RaisePropertyChanged("centertype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ContactDetails centercontactdetails {
            get {
                return this.centercontactdetailsField;
            }
            set {
                this.centercontactdetailsField = value;
                this.RaisePropertyChanged("centercontactdetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class GeoLocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int latitudeField;
        
        private int longitudeField;
        
        private string horizontalDatumField;
        
        private Height heightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string horizontalDatum {
            get {
                return this.horizontalDatumField;
            }
            set {
                this.horizontalDatumField = value;
                this.RaisePropertyChanged("horizontalDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Height height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class Height : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("altitude", typeof(Distance), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("verticalDatum", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("verticalLevel", typeof(sbyte), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class Distance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("blkDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("block", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dm", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ft", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ftDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("in", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("inDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("km", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("kmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("m", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mi", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("miDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mm", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("yd", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ydDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":blkDec")]
        blkDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":block")]
        block,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":dm")]
        dm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":dmDec")]
        dmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ft")]
        ft,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ftDec")]
        ftDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":in")]
        @in,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":inDec")]
        inDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":km")]
        km,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":kmDec")]
        kmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":m")]
        m,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mDec")]
        mDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mi")]
        mi,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":miDec")]
        miDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mm")]
        mm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mmDec")]
        mmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":yd")]
        yd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ydDec")]
        ydDec,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DateTimeZone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private string timeField;
        
        private string offsetField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DetectorStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Restrictions restrictionsField;
        
        private DeviceStatusHeader detectorstationstatusheaderField;
        
        private DetectorStatusDetectorlist detectorlistField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Restrictions restrictions {
            get {
                return this.restrictionsField;
            }
            set {
                this.restrictionsField = value;
                this.RaisePropertyChanged("restrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector-station-status-header", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DeviceStatusHeader detectorstationstatusheader {
            get {
                return this.detectorstationstatusheaderField;
            }
            set {
                this.detectorstationstatusheaderField = value;
                this.RaisePropertyChanged("detectorstationstatusheader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector-list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DetectorStatusDetectorlist detectorlist {
            get {
                return this.detectorlistField;
            }
            set {
                this.detectorlistField = value;
                this.RaisePropertyChanged("detectorlist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class DetectorStatusDetectorlist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DetectorStatusDetails[] detectorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DetectorStatusDetails[] detector {
            get {
                return this.detectorField;
            }
            set {
                this.detectorField = value;
                this.RaisePropertyChanged("detector");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0", ConfigurationName="TransportDevice.DevicePortType_v0p1")]
    public interface DevicePortType_v0p1 {
        
        // CODEGEN: Generating message contract since the operation publishDetectorStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Transport:SOAP:Device:Service#publishDetectorStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(C2CServer.TransportDevice.errorReport), Action="urn:Transport:SOAP:Device:Service#publishDetectorStatus", Name="errorReport", Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0p1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceStatusHeader_TMDD))]
        C2CServer.TransportDevice.publishDetectorStatusResponse1 publishDetectorStatus(C2CServer.TransportDevice.publishDetectorStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Transport:SOAP:Device:Service#publishDetectorStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<C2CServer.TransportDevice.publishDetectorStatusResponse1> publishDetectorStatusAsync(C2CServer.TransportDevice.publishDetectorStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation publishDMSStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Transport:SOAP:Device:Service#publishDMSStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(C2CServer.TransportDevice.errorReport), Action="urn:Transport:SOAP:Device:Service#publishDMSStatus", Name="errorReport", Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0p1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceStatusHeader_TMDD))]
        C2CServer.TransportDevice.publishDMSStatusResponse1 publishDMSStatus(C2CServer.TransportDevice.publishDMSStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Transport:SOAP:Device:Service#publishDMSStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<C2CServer.TransportDevice.publishDMSStatusResponse1> publishDMSStatusAsync(C2CServer.TransportDevice.publishDMSStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
    public partial class MsgContextCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgSolutionField;
        
        private string msgCorrelationIDField;
        
        private string msgTransactionField;
        
        private string msgSourceField;
        
        private string msgDestinationField;
        
        private string msgPriorityField;
        
        private System.DateTime msgTimestampField;
        
        private bool msgTimestampFieldSpecified;
        
        private ExtensionCType[] extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string msgSolution {
            get {
                return this.msgSolutionField;
            }
            set {
                this.msgSolutionField = value;
                this.RaisePropertyChanged("msgSolution");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string msgCorrelationID {
            get {
                return this.msgCorrelationIDField;
            }
            set {
                this.msgCorrelationIDField = value;
                this.RaisePropertyChanged("msgCorrelationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msgTransaction {
            get {
                return this.msgTransactionField;
            }
            set {
                this.msgTransactionField = value;
                this.RaisePropertyChanged("msgTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string msgSource {
            get {
                return this.msgSourceField;
            }
            set {
                this.msgSourceField = value;
                this.RaisePropertyChanged("msgSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string msgDestination {
            get {
                return this.msgDestinationField;
            }
            set {
                this.msgDestinationField = value;
                this.RaisePropertyChanged("msgDestination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=5)]
        public string msgPriority {
            get {
                return this.msgPriorityField;
            }
            set {
                this.msgPriorityField = value;
                this.RaisePropertyChanged("msgPriority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime msgTimestamp {
            get {
                return this.msgTimestampField;
            }
            set {
                this.msgTimestampField = value;
                this.RaisePropertyChanged("msgTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msgTimestampSpecified {
            get {
                return this.msgTimestampFieldSpecified;
            }
            set {
                this.msgTimestampFieldSpecified = value;
                this.RaisePropertyChanged("msgTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ExtensionCType[] extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
    public partial class ExtensionCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0p1")]
    public partial class publishDetectorStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private detectorStatusMsg detectorStatusMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tmdd.org/3/messages", Order=0)]
        public detectorStatusMsg detectorStatusMsg {
            get {
                return this.detectorStatusMsgField;
            }
            set {
                this.detectorStatusMsgField = value;
                this.RaisePropertyChanged("detectorStatusMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class detectorStatusMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DetectorStatus[] detectorstatusitemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector-status-item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DetectorStatus[] detectorstatusitem {
            get {
                return this.detectorstatusitemField;
            }
            set {
                this.detectorstatusitemField = value;
                this.RaisePropertyChanged("detectorstatusitem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0p1")]
    public partial class publishDetectorStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private C2cMessageReceipt c2cMessageReceiptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ntcip.org/c2c-message-administration", Order=0)]
        public C2cMessageReceipt c2cMessageReceipt {
            get {
                return this.c2cMessageReceiptField;
            }
            set {
                this.c2cMessageReceiptField = value;
                this.RaisePropertyChanged("c2cMessageReceipt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishDetectorStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
        public C2CServer.TransportDevice.MsgContextCType MsgContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0p1", Order=0)]
        public C2CServer.TransportDevice.publishDetectorStatus publishDetectorStatus;
        
        public publishDetectorStatusRequest() {
        }
        
        public publishDetectorStatusRequest(C2CServer.TransportDevice.MsgContextCType MsgContext, C2CServer.TransportDevice.publishDetectorStatus publishDetectorStatus) {
            this.MsgContext = MsgContext;
            this.publishDetectorStatus = publishDetectorStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishDetectorStatusResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
        public C2CServer.TransportDevice.MsgContextCType MsgContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0p1", Order=0)]
        public C2CServer.TransportDevice.publishDetectorStatusResponse publishDetectorStatusResponse;
        
        public publishDetectorStatusResponse1() {
        }
        
        public publishDetectorStatusResponse1(C2CServer.TransportDevice.MsgContextCType MsgContext, C2CServer.TransportDevice.publishDetectorStatusResponse publishDetectorStatusResponse) {
            this.MsgContext = MsgContext;
            this.publishDetectorStatusResponse = publishDetectorStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0p1")]
    public partial class publishDMSStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dMSStatusMsg dMSStatusMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tmdd.org/3/messages", Order=0)]
        public dMSStatusMsg dMSStatusMsg {
            get {
                return this.dMSStatusMsgField;
            }
            set {
                this.dMSStatusMsgField = value;
                this.RaisePropertyChanged("dMSStatusMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class dMSStatusMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DMSStatus[] dmsstatusitemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dms-status-item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DMSStatus[] dmsstatusitem {
            get {
                return this.dmsstatusitemField;
            }
            set {
                this.dmsstatusitemField = value;
                this.RaisePropertyChanged("dmsstatusitem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DMSStatus : DMSStatus_TMDD {
        
        private byte messagebeaconField;
        
        private bool messagebeaconFieldSpecified;
        
        private string messagebeacontypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-beacon", Order=0)]
        public byte messagebeacon {
            get {
                return this.messagebeaconField;
            }
            set {
                this.messagebeaconField = value;
                this.RaisePropertyChanged("messagebeacon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messagebeaconSpecified {
            get {
                return this.messagebeaconFieldSpecified;
            }
            set {
                this.messagebeaconFieldSpecified = value;
                this.RaisePropertyChanged("messagebeaconSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-beacon-type", Order=1)]
        public string messagebeacontype {
            get {
                return this.messagebeacontypeField;
            }
            set {
                this.messagebeacontypeField = value;
                this.RaisePropertyChanged("messagebeacontype");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMSStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DMSStatus_TMDD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Restrictions restrictionsField;
        
        private DeviceStatusHeader devicestatusheaderField;
        
        private string currentmessageField;
        
        private byte messagenumberField;
        
        private bool messagenumberFieldSpecified;
        
        private ushort messagetimeremainingField;
        
        private bool messagetimeremainingFieldSpecified;
        
        private string messagesourcemodeField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Restrictions restrictions {
            get {
                return this.restrictionsField;
            }
            set {
                this.restrictionsField = value;
                this.RaisePropertyChanged("restrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-status-header", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DeviceStatusHeader devicestatusheader {
            get {
                return this.devicestatusheaderField;
            }
            set {
                this.devicestatusheaderField = value;
                this.RaisePropertyChanged("devicestatusheader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("current-message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string currentmessage {
            get {
                return this.currentmessageField;
            }
            set {
                this.currentmessageField = value;
                this.RaisePropertyChanged("currentmessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public byte messagenumber {
            get {
                return this.messagenumberField;
            }
            set {
                this.messagenumberField = value;
                this.RaisePropertyChanged("messagenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messagenumberSpecified {
            get {
                return this.messagenumberFieldSpecified;
            }
            set {
                this.messagenumberFieldSpecified = value;
                this.RaisePropertyChanged("messagenumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-time-remaining", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ushort messagetimeremaining {
            get {
                return this.messagetimeremainingField;
            }
            set {
                this.messagetimeremainingField = value;
                this.RaisePropertyChanged("messagetimeremaining");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messagetimeremainingSpecified {
            get {
                return this.messagetimeremainingFieldSpecified;
            }
            set {
                this.messagetimeremainingFieldSpecified = value;
                this.RaisePropertyChanged("messagetimeremainingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-source-mode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string messagesourcemode {
            get {
                return this.messagesourcemodeField;
            }
            set {
                this.messagesourcemodeField = value;
                this.RaisePropertyChanged("messagesourcemode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0p1")]
    public partial class publishDMSStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private C2cMessageReceipt c2cMessageReceiptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ntcip.org/c2c-message-administration", Order=0)]
        public C2cMessageReceipt c2cMessageReceipt {
            get {
                return this.c2cMessageReceiptField;
            }
            set {
                this.c2cMessageReceiptField = value;
                this.RaisePropertyChanged("c2cMessageReceipt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishDMSStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
        public C2CServer.TransportDevice.MsgContextCType MsgContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0p1", Order=0)]
        public C2CServer.TransportDevice.publishDMSStatus publishDMSStatus;
        
        public publishDMSStatusRequest() {
        }
        
        public publishDMSStatusRequest(C2CServer.TransportDevice.MsgContextCType MsgContext, C2CServer.TransportDevice.publishDMSStatus publishDMSStatus) {
            this.MsgContext = MsgContext;
            this.publishDMSStatus = publishDMSStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishDMSStatusResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
        public C2CServer.TransportDevice.MsgContextCType MsgContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Device_v0p1", Order=0)]
        public C2CServer.TransportDevice.publishDMSStatusResponse publishDMSStatusResponse;
        
        public publishDMSStatusResponse1() {
        }
        
        public publishDMSStatusResponse1(C2CServer.TransportDevice.MsgContextCType MsgContext, C2CServer.TransportDevice.publishDMSStatusResponse publishDMSStatusResponse) {
            this.MsgContext = MsgContext;
            this.publishDMSStatusResponse = publishDMSStatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DevicePortType_v0p1Channel : C2CServer.TransportDevice.DevicePortType_v0p1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DevicePortType_v0p1Client : System.ServiceModel.ClientBase<C2CServer.TransportDevice.DevicePortType_v0p1>, C2CServer.TransportDevice.DevicePortType_v0p1 {
        
        public DevicePortType_v0p1Client() {
        }
        
        public DevicePortType_v0p1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DevicePortType_v0p1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevicePortType_v0p1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevicePortType_v0p1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        C2CServer.TransportDevice.publishDetectorStatusResponse1 C2CServer.TransportDevice.DevicePortType_v0p1.publishDetectorStatus(C2CServer.TransportDevice.publishDetectorStatusRequest request) {
            return base.Channel.publishDetectorStatus(request);
        }
        
        public C2CServer.TransportDevice.publishDetectorStatusResponse publishDetectorStatus(ref C2CServer.TransportDevice.MsgContextCType MsgContext, C2CServer.TransportDevice.publishDetectorStatus publishDetectorStatus1) {
            C2CServer.TransportDevice.publishDetectorStatusRequest inValue = new C2CServer.TransportDevice.publishDetectorStatusRequest();
            inValue.MsgContext = MsgContext;
            inValue.publishDetectorStatus = publishDetectorStatus1;
            C2CServer.TransportDevice.publishDetectorStatusResponse1 retVal = ((C2CServer.TransportDevice.DevicePortType_v0p1)(this)).publishDetectorStatus(inValue);
            MsgContext = retVal.MsgContext;
            return retVal.publishDetectorStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<C2CServer.TransportDevice.publishDetectorStatusResponse1> C2CServer.TransportDevice.DevicePortType_v0p1.publishDetectorStatusAsync(C2CServer.TransportDevice.publishDetectorStatusRequest request) {
            return base.Channel.publishDetectorStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<C2CServer.TransportDevice.publishDetectorStatusResponse1> publishDetectorStatusAsync(C2CServer.TransportDevice.MsgContextCType MsgContext, C2CServer.TransportDevice.publishDetectorStatus publishDetectorStatus) {
            C2CServer.TransportDevice.publishDetectorStatusRequest inValue = new C2CServer.TransportDevice.publishDetectorStatusRequest();
            inValue.MsgContext = MsgContext;
            inValue.publishDetectorStatus = publishDetectorStatus;
            return ((C2CServer.TransportDevice.DevicePortType_v0p1)(this)).publishDetectorStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        C2CServer.TransportDevice.publishDMSStatusResponse1 C2CServer.TransportDevice.DevicePortType_v0p1.publishDMSStatus(C2CServer.TransportDevice.publishDMSStatusRequest request) {
            return base.Channel.publishDMSStatus(request);
        }
        
        public C2CServer.TransportDevice.publishDMSStatusResponse publishDMSStatus(ref C2CServer.TransportDevice.MsgContextCType MsgContext, C2CServer.TransportDevice.publishDMSStatus publishDMSStatus1) {
            C2CServer.TransportDevice.publishDMSStatusRequest inValue = new C2CServer.TransportDevice.publishDMSStatusRequest();
            inValue.MsgContext = MsgContext;
            inValue.publishDMSStatus = publishDMSStatus1;
            C2CServer.TransportDevice.publishDMSStatusResponse1 retVal = ((C2CServer.TransportDevice.DevicePortType_v0p1)(this)).publishDMSStatus(inValue);
            MsgContext = retVal.MsgContext;
            return retVal.publishDMSStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<C2CServer.TransportDevice.publishDMSStatusResponse1> C2CServer.TransportDevice.DevicePortType_v0p1.publishDMSStatusAsync(C2CServer.TransportDevice.publishDMSStatusRequest request) {
            return base.Channel.publishDMSStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<C2CServer.TransportDevice.publishDMSStatusResponse1> publishDMSStatusAsync(C2CServer.TransportDevice.MsgContextCType MsgContext, C2CServer.TransportDevice.publishDMSStatus publishDMSStatus) {
            C2CServer.TransportDevice.publishDMSStatusRequest inValue = new C2CServer.TransportDevice.publishDMSStatusRequest();
            inValue.MsgContext = MsgContext;
            inValue.publishDMSStatus = publishDMSStatus;
            return ((C2CServer.TransportDevice.DevicePortType_v0p1)(this)).publishDMSStatusAsync(inValue);
        }
    }
}
