//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2CServer.TMCWeather {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Weather_v0p1")]
    public partial class errorReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorReport errorReportMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tmdd.org/3/messages", Order=0)]
        public ErrorReport errorReportMsg {
            get {
                return this.errorReportMsgField;
            }
            set {
                this.errorReportMsgField = value;
                this.RaisePropertyChanged("errorReportMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class ErrorReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Restrictions restrictionsField;
        
        private OrganizationInformation organizationinformationField;
        
        private OrganizationInformation organizationrequestingField;
        
        private string errorcodeField;
        
        private string errortextField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Restrictions restrictions {
            get {
                return this.restrictionsField;
            }
            set {
                this.restrictionsField = value;
                this.RaisePropertyChanged("restrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public OrganizationInformation organizationinformation {
            get {
                return this.organizationinformationField;
            }
            set {
                this.organizationinformationField = value;
                this.RaisePropertyChanged("organizationinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-requesting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public OrganizationInformation organizationrequesting {
            get {
                return this.organizationrequestingField;
            }
            set {
                this.organizationrequestingField = value;
                this.RaisePropertyChanged("organizationrequesting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
                this.RaisePropertyChanged("errorcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-text", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string errortext {
            get {
                return this.errortextField;
            }
            set {
                this.errortextField = value;
                this.RaisePropertyChanged("errortext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class Restrictions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string organizationinformationforwardingrestrictionsField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information-forwarding-restrictions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string organizationinformationforwardingrestrictions {
            get {
                return this.organizationinformationforwardingrestrictionsField;
            }
            set {
                this.organizationinformationforwardingrestrictionsField = value;
                this.RaisePropertyChanged("organizationinformationforwardingrestrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ntcip.org/c2c-message-administration")]
    public partial class C2cMessageReceipt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string informationalTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string informationalText {
            get {
                return this.informationalTextField;
            }
            set {
                this.informationalTextField = value;
                this.RaisePropertyChanged("informationalText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class ESSObservationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("pavement-data", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("subsurface-data", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("weather-data", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":pavement-data")]
        pavementdata,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":subsurface-data")]
        subsurfacedata,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":weather-data")]
        weatherdata,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class ESSObservationReportDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string esssensoridField;
        
        private DateTimeZone essobservationtimestampField;
        
        private ESSObservationType essobservationtypeField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ess-sensor-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string esssensorid {
            get {
                return this.esssensoridField;
            }
            set {
                this.esssensoridField = value;
                this.RaisePropertyChanged("esssensorid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ess-observation-timestamp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DateTimeZone essobservationtimestamp {
            get {
                return this.essobservationtimestampField;
            }
            set {
                this.essobservationtimestampField = value;
                this.RaisePropertyChanged("essobservationtimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ess-observation-type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ESSObservationType essobservationtype {
            get {
                return this.essobservationtypeField;
            }
            set {
                this.essobservationtypeField = value;
                this.RaisePropertyChanged("essobservationtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class DateTimeZone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private string timeField;
        
        private string offsetField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class Distance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("blkDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("block", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dm", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ft", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ftDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("in", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("inDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("km", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("kmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("m", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mi", typeof(short), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("miDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mm", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mmDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("yd", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ydDec", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":blkDec")]
        blkDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":block")]
        block,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":dm")]
        dm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":dmDec")]
        dmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ft")]
        ft,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ftDec")]
        ftDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":in")]
        @in,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":inDec")]
        inDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":km")]
        km,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":kmDec")]
        kmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":m")]
        m,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mDec")]
        mDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mi")]
        mi,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":miDec")]
        miDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mm")]
        mm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":mmDec")]
        mmDec,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":yd")]
        yd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":ydDec")]
        ydDec,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class Height : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("altitude", typeof(Distance), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("verticalDatum", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("verticalLevel", typeof(sbyte), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.LRMS-Adopted-02-00-00")]
    public partial class GeoLocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int latitudeField;
        
        private int longitudeField;
        
        private string horizontalDatumField;
        
        private Height heightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string horizontalDatum {
            get {
                return this.horizontalDatumField;
            }
            set {
                this.horizontalDatumField = value;
                this.RaisePropertyChanged("horizontalDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Height height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationCenterInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string centeridField;
        
        private string centernameField;
        
        private GeoLocation centerlocationField;
        
        private string centerdescriptionField;
        
        private string centertypeField;
        
        private ContactDetails centercontactdetailsField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string centerid {
            get {
                return this.centeridField;
            }
            set {
                this.centeridField = value;
                this.RaisePropertyChanged("centerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string centername {
            get {
                return this.centernameField;
            }
            set {
                this.centernameField = value;
                this.RaisePropertyChanged("centername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public GeoLocation centerlocation {
            get {
                return this.centerlocationField;
            }
            set {
                this.centerlocationField = value;
                this.RaisePropertyChanged("centerlocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string centerdescription {
            get {
                return this.centerdescriptionField;
            }
            set {
                this.centerdescriptionField = value;
                this.RaisePropertyChanged("centerdescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string centertype {
            get {
                return this.centertypeField;
            }
            set {
                this.centertypeField = value;
                this.RaisePropertyChanged("centertype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ContactDetails centercontactdetails {
            get {
                return this.centercontactdetailsField;
            }
            set {
                this.centercontactdetailsField = value;
                this.RaisePropertyChanged("centercontactdetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class ContactDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contactidField;
        
        private string personnameField;
        
        private string persontitleField;
        
        private string phonenumberField;
        
        private string phonealternateField;
        
        private string mobilephonenumberField;
        
        private string mobilephoneidField;
        
        private string faxnumberField;
        
        private string pagernumberField;
        
        private string pageridField;
        
        private string emailaddressField;
        
        private string radiounitField;
        
        private string addressline1Field;
        
        private string addressline2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipcodeField;
        
        private string countryField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contact-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contactid {
            get {
                return this.contactidField;
            }
            set {
                this.contactidField = value;
                this.RaisePropertyChanged("contactid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("person-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string personname {
            get {
                return this.personnameField;
            }
            set {
                this.personnameField = value;
                this.RaisePropertyChanged("personname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("person-title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string persontitle {
            get {
                return this.persontitleField;
            }
            set {
                this.persontitleField = value;
                this.RaisePropertyChanged("persontitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string phonenumber {
            get {
                return this.phonenumberField;
            }
            set {
                this.phonenumberField = value;
                this.RaisePropertyChanged("phonenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-alternate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string phonealternate {
            get {
                return this.phonealternateField;
            }
            set {
                this.phonealternateField = value;
                this.RaisePropertyChanged("phonealternate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mobile-phone-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string mobilephonenumber {
            get {
                return this.mobilephonenumberField;
            }
            set {
                this.mobilephonenumberField = value;
                this.RaisePropertyChanged("mobilephonenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mobile-phone-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string mobilephoneid {
            get {
                return this.mobilephoneidField;
            }
            set {
                this.mobilephoneidField = value;
                this.RaisePropertyChanged("mobilephoneid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fax-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string faxnumber {
            get {
                return this.faxnumberField;
            }
            set {
                this.faxnumberField = value;
                this.RaisePropertyChanged("faxnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pager-number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string pagernumber {
            get {
                return this.pagernumberField;
            }
            set {
                this.pagernumberField = value;
                this.RaisePropertyChanged("pagernumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pager-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string pagerid {
            get {
                return this.pageridField;
            }
            set {
                this.pageridField = value;
                this.RaisePropertyChanged("pagerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email-address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string emailaddress {
            get {
                return this.emailaddressField;
            }
            set {
                this.emailaddressField = value;
                this.RaisePropertyChanged("emailaddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("radio-unit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string radiounit {
            get {
                return this.radiounitField;
            }
            set {
                this.radiounitField = value;
                this.RaisePropertyChanged("radiounit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address-line1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string addressline1 {
            get {
                return this.addressline1Field;
            }
            set {
                this.addressline1Field = value;
                this.RaisePropertyChanged("addressline1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address-line2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string addressline2 {
            get {
                return this.addressline2Field;
            }
            set {
                this.addressline2Field = value;
                this.RaisePropertyChanged("addressline2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zip-code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
                this.RaisePropertyChanged("zipcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=18)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string organizationidField;
        
        private string organizationnameField;
        
        private string organizationlocationField;
        
        private string organizationfunctionField;
        
        private ContactDetails organizationcontactdetailsField;
        
        private OrganizationInformationCentercontactlist centercontactlistField;
        
        private DateTimeZone lastupdatetimeField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string organizationid {
            get {
                return this.organizationidField;
            }
            set {
                this.organizationidField = value;
                this.RaisePropertyChanged("organizationid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string organizationname {
            get {
                return this.organizationnameField;
            }
            set {
                this.organizationnameField = value;
                this.RaisePropertyChanged("organizationname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string organizationlocation {
            get {
                return this.organizationlocationField;
            }
            set {
                this.organizationlocationField = value;
                this.RaisePropertyChanged("organizationlocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-function", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string organizationfunction {
            get {
                return this.organizationfunctionField;
            }
            set {
                this.organizationfunctionField = value;
                this.RaisePropertyChanged("organizationfunction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ContactDetails organizationcontactdetails {
            get {
                return this.organizationcontactdetailsField;
            }
            set {
                this.organizationcontactdetailsField = value;
                this.RaisePropertyChanged("organizationcontactdetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public OrganizationInformationCentercontactlist centercontactlist {
            get {
                return this.centercontactlistField;
            }
            set {
                this.centercontactlistField = value;
                this.RaisePropertyChanged("centercontactlist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-update-time", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public DateTimeZone lastupdatetime {
            get {
                return this.lastupdatetimeField;
            }
            set {
                this.lastupdatetimeField = value;
                this.RaisePropertyChanged("lastupdatetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=7)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class OrganizationInformationCentercontactlist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrganizationCenterInformation[] centercontactdetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("center-contact-details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OrganizationCenterInformation[] centercontactdetails {
            get {
                return this.centercontactdetailsField;
            }
            set {
                this.centercontactdetailsField = value;
                this.RaisePropertyChanged("centercontactdetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tmdd.org/3/messages")]
    public partial class ESSObservationReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Restrictions restrictionsField;
        
        private OrganizationInformation organizationinformationField;
        
        private string stationidField;
        
        private ESSObservationReportEsssensorlist esssensorlistField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Restrictions restrictions {
            get {
                return this.restrictionsField;
            }
            set {
                this.restrictionsField = value;
                this.RaisePropertyChanged("restrictions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-information", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public OrganizationInformation organizationinformation {
            get {
                return this.organizationinformationField;
            }
            set {
                this.organizationinformationField = value;
                this.RaisePropertyChanged("organizationinformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("station-id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string stationid {
            get {
                return this.stationidField;
            }
            set {
                this.stationidField = value;
                this.RaisePropertyChanged("stationid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ess-sensor-list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ESSObservationReportEsssensorlist esssensorlist {
            get {
                return this.esssensorlistField;
            }
            set {
                this.esssensorlistField = value;
                this.RaisePropertyChanged("esssensorlist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class ESSObservationReportEsssensorlist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ESSObservationReportDetail[] esssensorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ess-sensor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ESSObservationReportDetail[] esssensor {
            get {
                return this.esssensorField;
            }
            set {
                this.esssensorField = value;
                this.RaisePropertyChanged("esssensor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Weather_v0", ConfigurationName="TMCWeather.WeatherPortType_v0p1")]
    public interface WeatherPortType_v0p1 {
        
        // CODEGEN: Generating message contract since the operation publishESSObservation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:PegaRULES:SOAP:Weather:Services#publishESSObservation", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(C2CServer.TMCWeather.errorReport), Action="urn:PegaRULES:SOAP:Weather:Services#publishESSObservation", Name="errorReport", Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Weather_v0p1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        C2CServer.TMCWeather.publishESSObservationResponse1 publishESSObservation(C2CServer.TMCWeather.publishESSObservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:PegaRULES:SOAP:Weather:Services#publishESSObservation", ReplyAction="*")]
        System.Threading.Tasks.Task<C2CServer.TMCWeather.publishESSObservationResponse1> publishESSObservationAsync(C2CServer.TMCWeather.publishESSObservationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
    public partial class MsgContextCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgSolutionField;
        
        private string msgCorrelationIDField;
        
        private string msgTransactionField;
        
        private string msgSourceField;
        
        private string msgDestinationField;
        
        private string msgPriorityField;
        
        private System.DateTime msgTimestampField;
        
        private bool msgTimestampFieldSpecified;
        
        private ExtensionCType[] extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string msgSolution {
            get {
                return this.msgSolutionField;
            }
            set {
                this.msgSolutionField = value;
                this.RaisePropertyChanged("msgSolution");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string msgCorrelationID {
            get {
                return this.msgCorrelationIDField;
            }
            set {
                this.msgCorrelationIDField = value;
                this.RaisePropertyChanged("msgCorrelationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msgTransaction {
            get {
                return this.msgTransactionField;
            }
            set {
                this.msgTransactionField = value;
                this.RaisePropertyChanged("msgTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string msgSource {
            get {
                return this.msgSourceField;
            }
            set {
                this.msgSourceField = value;
                this.RaisePropertyChanged("msgSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string msgDestination {
            get {
                return this.msgDestinationField;
            }
            set {
                this.msgDestinationField = value;
                this.RaisePropertyChanged("msgDestination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=5)]
        public string msgPriority {
            get {
                return this.msgPriorityField;
            }
            set {
                this.msgPriorityField = value;
                this.RaisePropertyChanged("msgPriority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime msgTimestamp {
            get {
                return this.msgTimestampField;
            }
            set {
                this.msgTimestampField = value;
                this.RaisePropertyChanged("msgTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msgTimestampSpecified {
            get {
                return this.msgTimestampFieldSpecified;
            }
            set {
                this.msgTimestampFieldSpecified = value;
                this.RaisePropertyChanged("msgTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ExtensionCType[] extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
    public partial class ExtensionCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Weather_v0p1")]
    public partial class publishESSObservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private eSSObservationReportMsg eSSObservationReportMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tmdd.org/3/messages", Order=0)]
        public eSSObservationReportMsg eSSObservationReportMsg {
            get {
                return this.eSSObservationReportMsgField;
            }
            set {
                this.eSSObservationReportMsgField = value;
                this.RaisePropertyChanged("eSSObservationReportMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tmdd.org/3/messages")]
    public partial class eSSObservationReportMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ESSObservationReport[] essobservationreportitemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ess-observation-report-item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ESSObservationReport[] essobservationreportitem {
            get {
                return this.essobservationreportitemField;
            }
            set {
                this.essobservationreportitemField = value;
                this.RaisePropertyChanged("essobservationreportitem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Weather_v0p1")]
    public partial class publishESSObservationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private C2cMessageReceipt c2cMessageReceiptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ntcip.org/c2c-message-administration", Order=0)]
        public C2cMessageReceipt c2cMessageReceipt {
            get {
                return this.c2cMessageReceiptField;
            }
            set {
                this.c2cMessageReceiptField = value;
                this.RaisePropertyChanged("c2cMessageReceipt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishESSObservationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
        public C2CServer.TMCWeather.MsgContextCType MsgContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Weather_v0p1", Order=0)]
        public C2CServer.TMCWeather.publishESSObservation publishESSObservation;
        
        public publishESSObservationRequest() {
        }
        
        public publishESSObservationRequest(C2CServer.TMCWeather.MsgContextCType MsgContext, C2CServer.TMCWeather.publishESSObservation publishESSObservation) {
            this.MsgContext = MsgContext;
            this.publishESSObservation = publishESSObservation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishESSObservationResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://transport.nsw.gov.au/tmc/schemas/software_component/SOAPHeader/v1")]
        public C2CServer.TMCWeather.MsgContextCType MsgContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport.nsw.gov.au/tmc/services/entity/devices/Weather_v0p1", Order=0)]
        public C2CServer.TMCWeather.publishESSObservationResponse publishESSObservationResponse;
        
        public publishESSObservationResponse1() {
        }
        
        public publishESSObservationResponse1(C2CServer.TMCWeather.MsgContextCType MsgContext, C2CServer.TMCWeather.publishESSObservationResponse publishESSObservationResponse) {
            this.MsgContext = MsgContext;
            this.publishESSObservationResponse = publishESSObservationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherPortType_v0p1Channel : C2CServer.TMCWeather.WeatherPortType_v0p1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherPortType_v0p1Client : System.ServiceModel.ClientBase<C2CServer.TMCWeather.WeatherPortType_v0p1>, C2CServer.TMCWeather.WeatherPortType_v0p1 {
        
        public WeatherPortType_v0p1Client() {
        }
        
        public WeatherPortType_v0p1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherPortType_v0p1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherPortType_v0p1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherPortType_v0p1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        C2CServer.TMCWeather.publishESSObservationResponse1 C2CServer.TMCWeather.WeatherPortType_v0p1.publishESSObservation(C2CServer.TMCWeather.publishESSObservationRequest request) {
            return base.Channel.publishESSObservation(request);
        }
        
        public C2CServer.TMCWeather.publishESSObservationResponse publishESSObservation(ref C2CServer.TMCWeather.MsgContextCType MsgContext, C2CServer.TMCWeather.publishESSObservation publishESSObservation1) {
            C2CServer.TMCWeather.publishESSObservationRequest inValue = new C2CServer.TMCWeather.publishESSObservationRequest();
            inValue.MsgContext = MsgContext;
            inValue.publishESSObservation = publishESSObservation1;
            C2CServer.TMCWeather.publishESSObservationResponse1 retVal = ((C2CServer.TMCWeather.WeatherPortType_v0p1)(this)).publishESSObservation(inValue);
            MsgContext = retVal.MsgContext;
            return retVal.publishESSObservationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<C2CServer.TMCWeather.publishESSObservationResponse1> C2CServer.TMCWeather.WeatherPortType_v0p1.publishESSObservationAsync(C2CServer.TMCWeather.publishESSObservationRequest request) {
            return base.Channel.publishESSObservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<C2CServer.TMCWeather.publishESSObservationResponse1> publishESSObservationAsync(C2CServer.TMCWeather.MsgContextCType MsgContext, C2CServer.TMCWeather.publishESSObservation publishESSObservation) {
            C2CServer.TMCWeather.publishESSObservationRequest inValue = new C2CServer.TMCWeather.publishESSObservationRequest();
            inValue.MsgContext = MsgContext;
            inValue.publishESSObservation = publishESSObservation;
            return ((C2CServer.TMCWeather.WeatherPortType_v0p1)(this)).publishESSObservationAsync(inValue);
        }
    }
}
